common: &common
  adapt.home:             ""
  adapt.is.local:         false
  adapt.db.adapter:       sqlite3
  adapt.db.path:          ""
  adapt.asset.path:       assets
  adapt.config.path:      /home/olaf/etc/adapt/config
  adapt.dir.mode:         0775
  adapt.file.mode:        0660
  adapt.file.ownership:   ""
  ada.openid.server:      http://users.ada.edu.au
  ada.registration.url:   http://users.ada.edu.au/users/new

development:
  <<: *common

production:
  <<: *common
  adapt.home:             /data/httpd/Rails/Adapt/shared
  adapt.config.path:      ""

stage:
  <<: *common
  adapt.home: adapt_stage

test: &test
  <<: *common
  adapt.asset.path:       tmp/test_assets

cucumber:
  <<: *test
