common: &common
  adapt.home:             ""
  adapt.asset.path:       assets
  adapt.dir.mode:         0775
  adapt.file.mode:        0660
  adapt.file.ownership:   ""
  ada.openid.server:      https://users.ada.edu.au
  ada.registration.url:   https://users.ada.edu.au/users/new
  ada.email.admin:        ada@anu.edu.au
  ada.email.webmaster:    olaf.delgado@gmail.com

development:
  <<: *common

test: &test
  <<: *common
  adapt.asset.path:       tmp/test_assets

deploy: &deploy
  <<: *common
  adapt.home:             /data/httpd/Rails/Adapt/shared
  adapt.file.ownership:   .d10

devs:
  <<: *deploy
  adapt.asset.path:       /projects_qfs/d10/assda/publish/ANU/Adapt/Test
  ada.openid.server:      https://users-test.ada.edu.au
  ada.registration.url:   https://users-test.ada.edu.au/users/new

staff:
  <<: *deploy
  adapt.asset.path:       /projects_qfs/d10/assda/publish/ANU/Adapt/Production
  adapt.archive.path:     /projects_qfs/d10/assda/publish/ANU/Archive
