common: &common
  adapt.home:             ""
  adapt.is.local:         false
  adapt.db.adapter:       sqlite3
  adapt.db.path:          ""
  adapt.asset.path:       assets
  adapt.config.path:      /home/olaf/etc/adapt/config
  adapt.dir.mode:         0775
  adapt.file.mode:        0660
  adapt.file.ownership:   ""
  assda.openid.server:    http://openid.assda.edu.au/joid/user/
  assda.openid.logout:    http://openid.assda.edu.au/joid/logout.jsp
  assda.registration.url: http://assda.anu.edu.au/online_reg.php

cucumber:
  <<: *common

development:
  <<: *common

production:
  <<: *common
  adapt.home: adapt

stage:
  <<: *common
  adapt.home: adapt_stage

test:
  <<: *common
