# Example database credentials file for ADAPT

template: &template
  username: moby
  password: dick

stage:
  <<: *template

production:
  <<: *template

development:
  <<: *template

test: &TEST
  <<: *template
  
cucumber:
  <<: *TEST
