<%
  require 'java'
  System = java.lang.System

  @app      = "tatwraps"
  @adapter  = ENV['RAILS_DB_ADAPTER'] ||
                System.getProperty('RAILS_DB_ADAPTER') || "sqlite3"
  @db_path  = ENV['RAILS_DB_PATH'] || System.getProperty('RAILS_DB_PATH')
  @home     = ENV['HOME'] || System.getProperty('user.home')

  def db_name(env)
    if @db_path
      name = @db_path
    elsif %w{mysql postgresql}.include? @adapter
      name = "#{@app}_#{env}"
    else
      base = if %w{stage production}.include?(env) then "#{@home}/#{@app}"
             else "." end
      name = "#{base}/db/db_#{env}.#{@adapter}"
    end
    #puts "# The database for #{env} is #{name}."
    name
  end
%>

template: &template
<% if @adapter == "sqlite3" %>
  adapter:  jdbcsqlite3
  timeout:  5000
<% elsif @adapter == "mysql" %>
  adapter: jdbcmysql
  encoding: utf8
  username: olaf
  password: g3h31m
<% elsif @adapter == "postgresql" %>
  adapter: jdbcpostgresql
  username: olaf
  password: g3h31m
<% elsif @adapter == "derby" %>
  adapter: jdbcderby
  username: app
  password: app
<% end %>

bootstrap:
  database: <%=db_name("bootstrap")%>
  <<: *template

stage:
  database: <%=db_name("stage")%>
  <<: *template

production:
  database: <%=db_name("production")%>
  <<: *template

development:
  database: <%=db_name("development")%>
  <<: *template

test: &TEST
  database: <%=db_name("test")%>
  <<: *template
  
cucumber:
  <<: *TEST
