development:
  adapter:  sqlite3
  database: db/db_development.sqlite3

test:
  adapter:  sqlite3
  database: db/db_test.sqlite3

# Our three deployment environments are devs, staff and public
deploy: &deploy
  adapter: postgresql
  port:     5432
  host:     <%= Secrets::DATABASE_HOST %>
  username: <%= Secrets::DATABASE_USERNAME %>
  password: <%= Secrets::DATABASE_PASSWORD %>

devs:
  <<: *deploy
  database: adapt_devs

staff:
  adapter:  sqlite3
  database: db/db_production.sqlite3
#  <<: *deploy
#  database: adapt_staff

public:
  <<: *deploy
  database: adapt_public
