development:
  :enable_starttls_auto: true
  :address: smtp.gmail.com
  :port: 587
  :authentication: login
  :user_name: grimley.fiendish@gmail.com
  :password: "Oh, damned!"
production:
  :address: smtp.server.com
  :port: 25
  :authentication: plain
  :user_name: user
  :password: pass
