gmail: &gmail
  :enable_starttls_auto: true
  :address: smtp.gmail.com
  :port: 587
  :authentication: login
  :user_name: user
  :password: pass

anusf: &anusf
  :address: anusf.anu.edu.au
  :port: 25
  :domain: assda.anu.edu.au

stage:
  <<: *anusf

production:
  <<: *anusf
