--- 
:data_kind: 
  :is_repeatable?: true
  :selections: 
    - Administrative / process-produced data
    - Audio-taped interviews
    - Case study notes
    - Census data
    - Clinical data
    - Coded documents
    - Correspondence
    - Educational test data
    - Election returns
    - Experimental data
    - Field notes
    - Focus group transcripts
    - Image
    - Interview notes
    - Interview summaries or extracts
    - Interview transcripts
    - Kinship diagrams
    - Minutes of meetings
    - Naturally occurring speech/conversation transcripts
    - Observational ratings/data
    - Photographs
    - Press clippings
    - Publications
    - Psychological test
    - Sound
    - Statistics/aggregate data
    - Survey data
    - Textual data
    - Time budget diaries/data
    - Video-taped interviews
:time_method: 
  :is_repeatable?: true
  :selections: 
    - one-time cross-sectional study
    - follow-up cross-sectional study
    - repeated cross-sectional study
    - longitudinal/panel/cohort study
    - time series
    - trend study
:sampling_procedure: 
  :is_repeatable?: true
  :selections: 
    - no sampling (total universe)
    - simple random sample
    - one-stage stratified or systematic random sample
    - multi-stage sample
    - multi-stage stratified random sample
    - one-stage cluster sample
    - area-cluster sample
    - quota sample
    - quasi-random (e.g. random walk) sample
    - purposive selection/case studies
    - volunteer sample
    - convenience sample
    - snowball
:collection_method: 
  :is_repeatable?: true
  :selections: 
    - clinical measurements
    - compilation or synthesis of existing material
    - diaries
    - educational measurements
    - email survey
    - face-to-face interview
    - observation
    - physical measurements
    - postal survey
    - psychological measurements
    - self-completion
    - simulation
    - telephone interview
    - transcription of existing materials
    - web-based self-completion
:depositors: 
  :subfields: 
    - name
    - affiliation
:principal_investigators: 
  :subfields: 
    - name
    - affiliation
  :is_repeatable?: true
:data_producers: 
  :subfields: 
    - name
    - affiliation
  :is_repeatable?: true
:funding_agency: 
  :subfields: 
    - agency
    - grant_number
  :is_repeatable?: true
:other_acknowledgements: 
  :subfields: 
    - name
    - affiliation
    - role
  :is_repeatable?: true
:references: 
  :subfields: 
    - citation
    - link
    - description
  :is_repeatable?: true
:affiliation:
  :selections:
    - Australian Catholic University
    - Australian National University
    - Bond University
    - Central Queensland University
    - Charles Darwin University
    - Charles Sturt University
    - Curtin University of Technology
    - Deakin University
    - Edith Cowan University
    - Flinders University
    - Griffith University
    - James Cook University
    - La Trobe University
    - Macquarie University
    - Monash University
    - Murdoch University
    - Queensland University of Technology
    - RMIT University
    - Southern Cross University
    - Swinburne University of Technology
    - University of Adelaide
    - University of Ballarat
    - University of Canberra
    - University of Melbourne
    - University of New England
    - University of New South Wales
    - University of Newcastle
    - University of Notre Dame Australia
    - University of Queensland
    - University of South Australia
    - University of Southern Queensland
    - University of Sydney
    - University of Tasmania
    - University of Technology Sydney
    - University of the Sunshine Coast
    - University of Western Australia
    - University of Western Sydney
    - University of Wollongong
    - Victoria University
